use USER_DB;

CREATE TABLE USERS(

    UserID INT NOT NULL AUTO_INCREMENT,
    UserName VARCHAR(255) NOT NULL,
    PRIMARY KEY (UserID)

);

CREATE TABLE HASHPASS(

    PassID INT NOT NULL AUTO_INCREMENT,
    HPass TEXT NOT NULL,
    UserID INT NOT NULL,

    PRIMARY KEY (PassID),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);

CREATE TABLE RECEIPTS(

    ReceiptID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    BuyDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ReceiptID),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);

CREATE TABLE ITEMS(

    ItemID INT NOT NULL AUTO_INCREMENT,
    ReceiptID INT NOT NULL,
    ItemName VARCHAR(255) NOT NULL,
    ItemCategory VARCHAR(255) NOT NULL,
    ItemPrice DECIMAL(15,2) NOT NULL DEFAULT 0,
    PRIMARY KEY(ItemID),
    FOREIGN KEY(ReceiptID) REFERENCES RECEIPTS(ReceiptID)

);

CREATE TABLE CORRECTIONS(

    UserID INT NOT NULL,
    ItemName VARCHAR(255) NOT NULL,
    Correction VARCHAR(255) NOT NULL,
    PRIMARY KEY(ItemName),
    FOREIGN KEY(UserID) REFERENCES USERS(UserID)

);


ALTER TABLE USERS AUTO_INCREMENT = 1;
ALTER TABLE HASHPASS AUTO_INCREMENT = 1;
ALTER TABLE RECEIPTS AUTO_INCREMENT = 1;
ALTER TABLE ITEMS AUTO_INCREMENT = 1;
ALTER TABLE CORRECTIONS AUTO_INCREMENT = 1;
